"""empty message

Revision ID: f097e7448cdf
Revises: 
Create Date: 2020-06-16 18:45:20.199218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f097e7448cdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Movie_Actor_id_fkey', 'Movie', type_='foreignkey')
    op.drop_column('Movie', 'Actor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movie', sa.Column('Actor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Movie_Actor_id_fkey', 'Movie', 'Actor', ['Actor_id'], ['id'])
    # ### end Alembic commands ###
